##
# @section DESCRIPTION
# Collects sources for a build.
##
Import('env')

# gather sources
l_sources = [ 'solvers/FWave.cpp',
              'solvers/Roe.cpp',
              'patches/WavePropagation1d.cpp',
              'patches/WavePropagation2d.cpp',
              'setups/DamBreak1d.cpp',
              'setups/DamBreak2d.cpp',
              'setups/RareRare1d.cpp',
              'setups/ShockShock1d.cpp',
              'setups/TsunamiEvent1d.cpp',
              'setups/ShockLand1d.cpp',
              'setups/CircularDamBreak1d.cpp',
              'io/Csv.cpp',
              'io/Stations.cpp' ]

if env['USE_NETCDF']:
  l_sources.append( 'io/NetCdf.cpp' )

for l_so in l_sources:
  env.sources.append( env.Object( l_so ) )

env.standalone_main = env.Object( "main.cpp" )
env.standalone_symmetry = env.Object( "symmetric_station_study.cpp" )

# gather unit tests
l_tests = [ 'tests.cpp',
            'solvers/FWave.test.cpp',
            'solvers/Roe.test.cpp',
            'patches/WavePropagation1d.test.cpp',
            'io/Csv.test.cpp',
            'setups/DamBreak1d.test.cpp',
            'setups/RareRare1d.test.cpp',
            'setups/ShockShock1d.test.cpp' ]

for l_te in l_tests:
  env.tests.append( env.Object( l_te ) )

Export('env')